### ISSUE TITLE
Server-side-only version?

### ISSUE THREAD

**Issue by NebelNidas** [sf-inc/sihywtcamd#1]
> File needed for both client and server!

Why is that? From what I could read, the changes only affect mob stats and behavior, which should be implementable server-side-only?

**Comment by charlyb01** [comment]
I didn't take time to test for now that's why. But I guess it can be implemented server side only: the only change that you will miss is the phantom translucent texture. If you want you can try before I do, there should be no problem ;)

**Comment by charlyb01** [comment]
It works server-side only as mentionned in the updated description on CurseForge.
But note that if you don't have it client-side, you won't see the translucent texture of phantoms, and baby spiders will appear as big as normal ones.
