### ISSUE TITLE
How do I disable zombie type buffed?

### ISSUE THREAD

**Issue by deftesthawk** [sf-inc/sihywtcamd#13]
In the config it says:

"zombieTypeBuffed": "ALL"

What would I have to change the "ALL" to so I can disable it, also what other things can I type in that field?

**Comment by charlyb01** [comment]
The "zombieTypedBuffed" is for the buff of zombie-like mobs so they can't get true damage without being on fire, or using smite (see more on the mod [description](https://www.curseforge.com/minecraft/mc-mods/sihywtcamd)). The values it can take are : NONE, ZOMBIE_ONLY, NO_DROWNED, NO_PIGLIN, and ALL, as explained in the [changelog](https://github.com/sf-inc/sihywtcamd/blob/master/CHANGELOG.md#configs). You can change easily the configs using the [Mod Menu](https://www.curseforge.com/minecraft/mc-mods/modmenu) if you're not on a server.
* NONE : deactivate the feature
* ZOMBIE_ONLY : zombie, zombie villager,  zombie horse (can't spawn naturally but exists in game), giant (same but don't have an ai in game)
* ALL : ZOMBIE_ONLY + drowned, zombified piglin, husk
* NO_DROWNED : ALL - drowned
* NO_PIGLIN : ALL - zombified piglin

I will add it to the description to be more clear

**Comment by deftesthawk** [comment]
Thanks for the info, I managed to guess the NONE I might mess around with the setting now I know a bit more about what I can do with it. Thanks :)

**Comment by charlyb01** [comment]
I just opened a Discussions tab on the github project if you have any other things to share =)
