### ISSUE TITLE
[Bug] Frozen Phantoms

### ISSUE THREAD

**Issue by RyanCR03** [sf-inc/sihywtcamd#27]
phantoms don't have flapping animations or a red flash when hit. even when translucency is turned off

**Comment by charlyb01** [comment]
Oh thanks for the report! I will check that, thank you

**Comment by charlyb01** [comment]
So about the flapping animation, I'm not sure to understand. When you hit a phantom, it goes back in the air, looking up, and it's the same with the mod. For the red flash, you're right! It will be fixed in the next update =)
