### ISSUE TITLE
[Suggestion] Some Mobs Spawn Naturally everywhere

### ISSUE THREAD

**Issue by RyanCR03** [sf-inc/sihywtcamd#28]
Slimes will spawn naturally everywhere. (Large and Extra Large Slimes are only in swamps and slime chunks)

Blazes and Wither Skeletons naturally spawn in Nether Wastes biomes.

**Comment by charlyb01** [comment]
I'm not so sure about the idea... I need to take the time to think more about it, but thanks for the suggestion!

**Comment by charlyb01** [comment]
For all of those, this would add too much help for farming to my mind.
For slimes, it would also become harder to detect an actual slime chunk.
For blazes, this would also become terrible to play in my opinion.
I'm sorry but I won't add those for these reasons. Also, I don't have a lot of time for modding anymore.
