### ISSUE TITLE
Idea: Illager patrol buffs

### ISSUE THREAD

**Issue by saltyseadoggo** [sf-inc/sihywtcamd#3]
On the Bedrock Edition, Illager patrols that spawn have 20% of their pillagers replaced with vindicators on Hard difficulty ([source](https://minecraft.fandom.com/wiki/Vindicator#Patrols)). This feature makes Illager patrols a bit more dangerous due to containing melee mobs instead of just ranged ones, but the feature does not exist on the Java edition.

I think that porting this Bedrock feature would be a good fit for this mod due to making patrols more dangerous, especially when combined with the buffs to the vindicator already in the mod. The difficulty-specific limitation could be removed, making 20% of all patrollers vindicators on all difficulties.

Patrols could also have a chance to rarely spawn with a ravager, with or without a riding pillager.

**Comment by charlyb01** [comment]
Oh I'm sorry to have not reply before, I didn't see it and was quite busy!
I really like the idea of 20%. I think I will keep the difficulty limitation but maybe replaced with the local difficulty. I may add also the ravager but extremely rare as it's quite powerful. Thanks again for the idea =)

**Comment by charlyb01** [comment]
Check the commit description to know more
