### ISSUE TITLE
Are your mod is spawning mobs with Armours?

### ISSUE THREAD

**Issue by TheButterbrotMan** [sf-inc/sihywtcamd#31]
Since i installed your mod, my mobs are spawning with armour, and the armor get completly dropped when the mobs are die.

**Comment by TheButterbrotMan** [comment]
Additional some mobs are glowing? Is this also caused by your mod? Can you add a config to disable this?

**Comment by charlyb01** [comment]
Hi, I will need more info about the mods you installed.

* Mobs can spawn with armour in vanilla minecraft. It depends on the local difficulty: the more you stay in a place, the more likely it is that there spawn mobs with armours. I didn't change anything about rate of spawn or anything related.
* Mobs can have glowing effect in only two ways in vanilla and I didn't add any behavior related to glowing:
  * You hit them with a spectral arrow
  * Pillagers close to a bell you're ringing during a raid

So my best guess is that you installed other mods modifying the mobs. Hope it helped =)
