### ISSUE TITLE
Lots of suggestions!

### ISSUE THREAD

**Issue by kxkxrxtx** [sf-inc/sihywtcamd#33]
I LOVE your mod, I can't play without it and I would like to make some suggestions inspired on other mods that I think would fit very well with your take. I'm just brainstorming so take my approaches with all the salt you need. Here are some of them:

### Undead category.
- **Every adult and baby zombie**: They know how to climb ladders and also will properly hide from the sun, waiting for the next moon.
- **Every baby zombie**: Their playfully evil nature would make them steal the items the player is holding.
- **Every skeleton**:  They are immune to normal projectiles (no organs) and will prevent shoot spaming if you hold your shield.

- **Zombies**:
   - Now, they have different AIs, giving them more personality: they are slower, but will always gain a speed boost if they burn and if Fabric/Forge: Zombie Horse Spawn is installed. Also, brainless zombies now can spawn as neutral who will wander around aimlessly.
   - Their lust of blood let heal themselves on a succesful attack to the player, on the same proportion the damage they deal. Also, they have natural knockback resistance.
   - Zombie siege ones will try to reach their target, destroying any wooded door/fence gate in their path.

- **Baby zombies**:
   - The most unpopular mob now will pounce to their targets, like spiders, because of their size and will try to "parkour", jumping blocks to reach you. And so, they have a reduced knockback resistance.

- **Baby drowned**:
   - They will have the chance to spawn as a guardian jockey.

- **Adult husks**: 
   - Masters of the cursed sands, they have a chance to bury the player on a sand block, making them collapse underground. Or optionally, they surround the player with sand columns, instead of pulling.
   - In an ideal situation, they would remove the 3x3x3 blocks below the player, leaving the 3x1x3 sand blocks around the player is standing on, making a hole on the ground to be impossible for the player to escape. This wouldn't work for a layer below Y<48.

- **Zombie villagers**:
   - They show their grudge to the living targeting every animal and every crop (except beetroots because no one cares about them lol, giving them an actual advantage). If they attack a horse, it will transform to a zombie horse. And if they land a succesful attack on the player, they will give the Bad Omen effect.

- **Zombified piglins**:
   - Rarely, if a player enters in their nearby area (2, 3 blocks away) they will absolutely berserk.
   - In the overworld, they will haunt pigs aggressively to transform them into one of their kind. Their ultimate purpose will be to destroy their natural enemies: pillagers and villagers, transforming the latter into their zombie variation.
   - In the same line of villagers, now they can be dezombified but with a golden carrot.

- **Skeletons**: 
   - They can follow you underwater, because why they wouldn't?
   - Normal skeletons have a low probability of carrying glow arrows with them, ensuring every other enemy knows you are there.
   - Spider jockeys have an increased chance to appear and will bring instant damage tipped arrows with them, prioritizing the needs of their undead allies if their health is too low.
   - The dreadful skeleton horseman which appear during a thunderstorm are now faster and will occasionally shoot thunder arrows at you, having no place to you to hide.
   - **NEW: Baby skeleton**: normal skeletons with normal arrows. They shoot quick volleys at you, reducing the charge between shots at the price of less accuracy. Oh, and they have a chance of spawn as bat jockeys.

- **Strays**: 
   - The frozen watchmen will shoot instant freezing effect arrows, in top of their slow effect.

- **Wither skeletons**:
   - Every skeleton who reach the nether will transform to a wither skeleton.
   - Demons incarnated, now they are fire resistant and hold netherite swords. Run.

### Arthropods
- **Every arthropod**: No damage from falling and aggro for every fleshy villager.
- **Every larvae**: They're twice as fast.

- **Spiders**: nothing at all. You made them perfect <3

- **Cave spiders**:  
   - Ancient workers died because they couldn't escape from these horrifying bugs, giving them poison, weakness, nausea and mining fatigue. Deeper means deadlier.

- **Silverfish**: 
   - They plagued the underground and now live everywhere. Watch out yourself.
   - If by any mean they reach The End, they will addopt their endermite cousin appereance.

- **Endermites**: 
   - They will appear in chorus trees forest; this chance is increased if you break infested chorus trees, which will fall from them.
   - Having sucked chorus fruits since eternity, now they have the power to teleport you at a random near location.
   - And least and most important, if they manage to stand on a purpur variant block for a moment, they will grow from their larva stage to an indefinite Shulker pupa.
   
- **Shulkers**:
  - Attacking their impenetrable shell directly with your melee weapons will hurt your hands and weaken you. And don't think to try it while they're closed, they will take no damage.
  - And like their younger stages, stay away from their projectiles, because now they will teleport you  away from their nest to keep it safe from you.

### Slimes:
- **Every slime**: 
   - Their chunky bodies will negate fall damage and reflect projectiles. 
   - The bigger they are, the slower but stronger, and viceversa.

- **Slimes**: 
   - Depending on their size, they will fling the player away on hit. 
   - Their mucus will inflict slowness, stacking this effect with every hit. Nasty.
   - Dealing damage with you weapon have the chance that it will stack on their body. Killing them will return your item back.
   - They will absorb magma blocks to transform to their nether variant.

- **Magma blocks**:
   - Made of magma, they will ignite the player on contact.
   - Biggest ones will melt every stone block where they land, turning them to a magma block.
   - When killed, they will spread a small amount of lava.
   - They will cool down if they land on a slime block or fall in water, returning them to their regular form.

### Ghost-like:
   - **Every ghost-like**: Because of their incorporeal body, they're immune to mundane weapons. Enchanted weapons will be the only way to inflict them damage.
   
- **Phantoms**: 
   - Coming from the above dimension, their natural home is located in The End. They're nests are located in end cities, where they spawn more frequently.

- **Vexes**:
   - They wander in the dark... I mean, the dark forest.
   - These tricksters inflict darkness on hit to steal your gear.
   - Fortunately, invocated vexes will with their evoker master.

I will continue if you like to hear more from my ideas. Thank you so much! <3

**Comment by charlyb01** [comment]
Wohhh! That's a lot, you didn't lie 😆 
I love your ideas, all of them. I'm not gonna lie too, it's going to take some time but I will definitely add them. I'm going to start very soon, but first I may split some in order to keep track of what I'm doing and where I'm going. We can totatlly talk about more ideas if you have, don't hesitate to join my [Discord](https://discord.gg/eNwkve8k7c) to talk about it with me and maybe some other members 😉 
But with all of those changes, I guess I will need to rework again the configs and offer some config presets to be less a pain to set up ^^

**Comment by charlyb01** [comment]
Many suggestions were added to [v1.7](https://github.com/sf-inc/sihywtcamd/blob/master/CHANGELOG.md#v17) and some other may come in the next update but as you're written down those suggestions on the discord server, I will close the issue there and make some other in the future with features I may add later =)
