### ISSUE TITLE
Modrinth Posting?

### ISSUE THREAD

**Issue by ryleu** [sf-inc/sihywtcamd#41]
Hello! Love your mod, but I want to include it in a modrinth modpack. Curseforge is a pretty awful platform now, so the switch may benefit your sanity as well. 

Would you consider posting to Modrinth too (or instead)?

**Comment by charlyb01** [comment]
It should be soon available [here](https://modrinth.com/mod/difficulty).

I guess I will post all my mods there. I will keep CurseForge for 1.20, I will see later if I can stop CurseForge. Thanks again!
