### ISSUE TITLE
Game Crashing with Bygone Nether

### ISSUE THREAD

**Issue by Killercrab432** [sf-inc/sihywtcamd#42]
Game instantly crashes when i go near the Piglin Manor in Bygone Nether 1.18.2 Fabric

https://pastebin.com/9K5jPZHZ

**Comment by charlyb01** [comment]
Thanks for reporting! I will check this mod too when fixing the issue.
Duplicate of #38.

**Comment by Killercrab432** [comment]
Issue seems to still be present on 1.20.1 using 1.7.5 version of your mod https://pastebin.com/h0XvuUjS any hope for a fix?
