### ISSUE TITLE
World freeze when generating structure (Fixed in 1.7.5 and later)

### ISSUE THREAD

**Issue by liangmoe** [sf-inc/sihywtcamd#43]
the error is provided by modernfix, and yes after removed sihywtcamd and world no longer freeze. the moment that world freeze is creating new chunk in the same area.
the server log:
[2023-11-13-3.log](https://github.com/sf-inc/sihywtcamd/files/13336229/2023-11-13-3.log)

**Comment by charlyb01** [comment]
This is a known issue, see #38. This was fixed in latest version. I may backport the fix for 1.19, but this was not originally planned

**Comment by liangmoe** [comment]
can i disable somthing in the config to prevent freezing for now? or i need to entirely remove the mod

**Comment by charlyb01** [comment]
Sure, you can disable the zombie `drowned.guardianJockeySpawn` option, which allows baby Drowned to spawn riding a Guardian, and the nether `piglin.rideHoglin` option, which allows Piglin to spawn riding a Hoglin.  
This should be enough. Let me know if it isn't.

NB: Make sure these option are disabled on the server-side.

**Comment by liangmoe** [comment]
I think we can close this issue after a month  playing, everything works as intended and have never crashed. And i would likely bump up my minecraft version so no backport hotfix is fine for me, thanks again for the help, love you!
