### ISSUE TITLE
Crash from mixins error

### ISSUE THREAD

**Issue by VeggeieDude** [sf-inc/sihywtcamd#46]
Heya! When I try to load a world, my game will crash and it only happens when I try to use the SIHYWTCAMD mod. The log mentions a mixin error involving Cardinal Components.

I'm the using the latest 1.20.2 version, here are my logs:
[crash-2024-01-16_03.59.48-client.txt](https://github.com/sf-inc/sihywtcamd/files/13947707/crash-2024-01-16_03.59.48-client.txt)

Hope this helps, ty!

**Comment by charlyb01** [comment]
Hello and thanks for the report! Actually, I guess this is only because you're using the wrong mod version. Indeeed, your minecraft version is 1.20.1 but you're playing with a 1.20.2 mod version. I think the Cardinal Component API is not compatible between these two minecraft version, which cause the crash.

**Comment by VeggeieDude** [comment]
Oooh! Lol sorry 😂

I downloaded the newest version because I saw it fixed a problem with creepers giving you a permanent status.

Is that issue in the 1.20.1 version? Or if I disable creepers giving you negative statuses, will it get rid of the issue?

**Comment by charlyb01** [comment]
No problem! Yes, there is the problem in the 1.20.1 version, but you may as well never encounter it. This is an issue that happens only with a very specific distance condition when the creeper explodes, and this is not a big issue actually. It's just a visual artifact. The client can have the effect displayed, but the server knows if it should still apply and so it doesn't affect gameplay at all. You can get rid of the effect display if you encounter the issue by just reconnecting to the world.

**Comment by VeggeieDude** [comment]
Oooh ok! Tyty for the quick responses!
