### ISSUE TITLE
Zombie Piglins are always aggro'd

### ISSUE THREAD

**Issue by VeggeieDude** [sf-inc/sihywtcamd#47]
Hey again lol. So after playing around with this mod a bit more, I found that zombie piglins are always angry and aggro'd on you no matter what with SIHYWTCAMD installed.

I'm still on the latest 1.20.1 fabric version.

Removing the mod fixed it,

**Comment by VeggeieDude** [comment]
Sorry! I fixed it, it wasn't your mod lol my bad

**Comment by charlyb01** [comment]
Alright, thanks for clising the issue if it wasn't related to my mod :)
