### ISSUE TITLE
Mobs do not spawn

### ISSUE THREAD

**Issue by RocioKanmi** [sf-inc/sihywtcamd#48]
Well i put this mod on my mod list and once i started the world, hostile mobs didn't spawn, after a few minutes i remove the mod and start again the world and mobs start to spawn.

Im not sure, but is like this mod disable the spawn of hostile mobs

**Comment by charlyb01** [comment]
Hello, what was your issue? Was the issue from another mod or was it an incompatibility?

**Comment by RocioKanmi** [comment]
> Hello, what was your issue? Was the issue from another mod or was it an incompatibility?

idk what it was, but for say in other words i was touching the config settings. I wanted to disable the option to make hostile mobs to attack villagers (which option i never found) and i touch other config that one disable the spawn of mobs. So i was sending this tread wrongly because i fixed putting in true again. 

{
  "general": {
    "mobsLessFear": true,
    "merchantHostility": true
  }

the meerchanthostility if i put on false disable every hostile mob from the game to prevent it spawn. But... since u send me a message, could you help me?, which option on the config i have to turn in false to disable the option to make hostile mobs to attack villagers?.

**Comment by charlyb01** [comment]
That's funny, I just replied to you on CurseForge.

There is no option in config files that should disable the spawn of mobs. If I understand correctly, when you put this to false `"merchantHostility": false`, hostile mobs don't spawn anymore? If yes, this is a bug. I will do some testing.  
But you were right, this is the option you should disable if you don't want hostile mobs to attack villagers. Note that it disables only the one I added this behavior to, but not the ones that had it already, such as zombies.

**Comment by RocioKanmi** [comment]
> That's funny, I just replied to you on CurseForge.
> 
> There is no option in config files that should disable the spawn of mobs. If I understand correctly, when you put this to false `"merchantHostility": false`, hostile mobs don't spawn anymore? If yes, this is a bug. I will do some testing. But you were right, this is the option you should disable if you don't want hostile mobs to attack villagers. Note that it disables only the one I added this behavior to, but not the ones that had it already, such as zombies.
> 
> [EDIT] After small testing, disabling it disables the behavior without breaking mob spawn. Feel free to give me more info about it

oh, alright. Im gonna check again this night. Maybe was just a coincidence but honestly im not sure, i was walking in the night far away from my house and mobs never spawned when i turn in false the ``merchanhostility``. But when i turn on again mobs started to spawn like normally.
Im gonna check it and i tell you news about it c:

BTW, I forget, the mod version i was playing it was the latest one for 1.20.1.
