### ISSUE TITLE
Bygone Nether still incompatible

### ISSUE THREAD

**Issue by Killercrab432** [sf-inc/sihywtcamd#49]
Issue in https://github.com/sf-inc/sihywtcamd/issues/42
seems to still be present on 1.20.1 using 1.7.5 version of your mod https://pastebin.com/h0XvuUjS any hope for a fix?

**Comment by charlyb01** [comment]
Hello, thanks for the report! I thought this was completely fixed... I'll check what's wrong and release a fix. Should I backport current release in 1.20.1 with the fix in the meantime?

**Comment by Killercrab432** [comment]
that would be amazing if you did that tysm ❤️

**Comment by charlyb01** [comment]
Found the issue, it was slightly different than what I fixed, but the result was the same.  
This should now be fixed hopefully in the next version

**Comment by Killercrab432** [comment]
Awesome news, tysm

**Comment by charlyb01** [comment]
Fix released on both 1.20.4 and 1.20.1, with port to latest mod version for 1.20.1 😉
