### ISSUE TITLE
Compatibility issue with "frycmobvariants"

### ISSUE THREAD

**Issue by ImWhiff** [sf-inc/sihywtcamd#51]
I am crashing with the new update (1.10) after couple minutes of playing on a world. I do have lots of mods installed, but the previous update (1.9.1) doesn't cause me to crash. Not sure if it's a compatibility issue or not, but I noticed something with the [Dungeon Difficulty](https://www.curseforge.com/minecraft/mc-mods/dungeon-difficulty) mod by daedelus_dev and this mod: "

java.lang.NullPointerException: Cannot invoke "net.minecraft.class_2945$class_2946.method_12794()" because the return value of "net.minecraft.class_2945.method_12783(net.minecraft.class_2940)" is null
at net.minecraft.class_1639.handler$koi001$sihywtcamd$makeEyeHeightDependsOnSize(class_1639.java:1555)
at net.minecraft.class_1917.handler$dfo000$dungeon_difficulty$pre_serverTick(class_1917.java:2045)

"
Log: [2024-03-29-2.log.gz](https://github.com/sf-inc/sihywtcamd/files/14800480/2024-03-29-2.log.gz)

**Comment by charlyb01** [comment]
Hello and thanks for the report! It looks indeed like a compatibility issue. However, I believe it's not with `dungeon_difficulty` but with `frycmobvariants`. Do you know to which mod it corresponds? I think I know exactly the cause, however I need to investigate how to solve it

**Comment by charlyb01** [comment]
I found out how to solve the issue. Before releasing it in a new minor version, I will apply this change to some other part of the code that could meet the same compatibility issue in order to make the mod even more robust.

**Comment by ImWhiff** [comment]
Yep that's the mod. 

Also sounds good. Thanks for looking into the issue so quick and for the great mod!

 I'll leave it to you to close the issue.
