### ISSUE TITLE
Server crash v1.10

### ISSUE THREAD

**Issue by tacogerbil** [sf-inc/sihywtcamd#52]
**Minecraft 1.20.1 with Fabric Loader 0.15.7**
Added **sihywtcamd-1.10+1.20.1.jar** and I started getting a crash.. It's a large custom modpack I'm using (240 mods or so) and I was impressed by your mod's Description.
Unfortunately a few minutes on my personal server with my son leads to a crash....  The log file doesn't show anythig except generic complaints about ticks taking too long, afterwhich it crashes with a watchdog error **at net.minecraft.class_8.handler$edp000$sihywtcamd$updateMobSize(class_8.java:532)**
https://pastebin.com/LJjULhcc <--crash log

**Comment by charlyb01** [comment]
Hello, thanks for the report! This bug was shared to me on my Discord recently. I made a fix that I'm going to release very soon. Sorry for the inconvenience! You can disable General `pathPassengerAware` or set Zombie `babyTowerHeight` to maximum 1 to avoid the crash before I release the fix

**Comment by tacogerbil** [comment]
Thank you!  😁
![image](https://github.com/sf-inc/sihywtcamd/assets/12961907/b7d86120-ef7c-4f0d-b1c5-8e7a760cb469)
