### ISSUE TITLE
Fabric 1.21 - some thing are waterlogged? 

### ISSUE THREAD

**Issue by pewblaze** [sf-inc/sihywtcamd#56]
Hi, with the newest version some things are looking like that:
same for chests, some leaves in a biomesoplenty biome or some other stuff i guess.
it works fine with sihywtcamd-1.10.3+1.21.jar

![2024-08-16_10 35 50](https://github.com/user-attachments/assets/591ef8e4-f22f-4442-8c49-c032f5f3f3ce)

My client log if needed:
https://gist.github.com/pewblaze/b5ce0ec9552edb70c5a742de7ad6b5d3

**Comment by charlyb01** [comment]
Hi, thanks for the report. What am I looking at exactly, are you talking about blocks not waterlogged?

**Comment by charlyb01** [comment]
Mmh I wasn't able to reproduce with my mod alone. Are you sure the issue is my mod? Did you try to reinstall the previous version to see if you still had the issue?

**Comment by pewblaze** [comment]
So i updated a few mods in the meantime & the waterlogged stuff is gone. sorry about that! cant say which mod triggered this but its fine now :D
