### ISSUE TITLE
Wrong blocks tags/id with other mods (v1.10.4)

### ISSUE THREAD

**Issue by Toimis** [sf-inc/sihywtcamd#57]
Hello,

I play with a decently large modpack and noticed at some point after updating mods that my friends were experiencing issues. It seemed like blocks had ID mismatches or something, causing them to appear as waterlogged or as entirely different blocks for them, but normal for me (since I play singleplayer and open the world using Essential when they have time to play).

The issue is reproducible for me with only Fabric API, SIHYWTCAMD, and Wilder Wild. If you join a random server (I used Hypixel), you will notice some crazy stuff happening. I have not tried reproducing on a fresh install, so it's probably a lost cause if you cannot because I had over 100 mods at some point lol.

I will also be reporting this issue to the Wilder Wild repository.

Thank you!

PS: Love the mod, and appreciate the work you put in!
![Screenshot 2024-08-21 051924](https://github.com/user-attachments/assets/479677d1-a18c-4701-aadd-55b850a66be6)
![Screenshot 2024-08-21 051727](https://github.com/user-attachments/assets/d8e04a31-6026-49a1-9cd3-bc55ad3d6c9e)
[latest.log](https://github.com/user-attachments/files/16691376/latest.log)

**Comment by charlyb01** [comment]
Hi, thanks for the report! This looks like the same issue than #56. The player just updated other mods and it seemed to fix its issue. I will try to reproduce with wilderwild though to know if there is something more

**Comment by charlyb01** [comment]
Hi, I've done a little bit of testing. I didn't reproduce on singleplayer but I did on server. However, I encountered the issue only when I had Wilder Wild installed. Difficulty only did not **seem** to create block mismatches (maybe it did but as I add only one block, maybe only one is mismatched). Anyway, I think the issue you're having with your friends is that you're not playing with the mods setup in terms of mods adding new blocks, either missing mods or different versions. Can you confirm?

**Comment by Toimis** [comment]
No, we all play with the same mods using my GitHub repository found here: https://github.com/Toimis/MC1.21

And this batch script I made with AI lol
[update2.txt](https://github.com/user-attachments/files/16719566/update2.txt)

**Comment by Linguardium** [comment]
> If you join a random server (I used Hypixel), you will notice some crazy stuff happening

Content mods change the registered blocks and renderers. If you join a non-fabric server that does not sync that data (like hypixel), then your game will render blocks incorrectly. This is why mismatched mod versions can cause the issue as well. This is not an issue with this mod nor wilder wilds, its a problem with trying to use mods on servers with different or missing mods

**Comment by Toimis** [comment]
> This is not an issue with this mod nor wilder wilds, its a problem with trying to use mods on servers with different or missing mods

I was having this issue even with my friends, who sync their mods completely the same though? Is it because of something with Essential hosting? I'm going to start using Aternos or port-forwarding so I'll see what I can find out, but everyone else stopped playing

**Comment by charlyb01** [comment]
Having client-side mods is not the issue. As we both mentioned, the issue should come from different (server) mods registering new blocks and/or different configs. If you all have the exact same configs for the exact same (server) mods, then the issue might come from Essential that doesn't sync properly the data when opening the multiplayer.

**Comment by Toimis** [comment]
Okay, so I was able to get my own server running that I port-forwarded, hosted on my laptop, and joined on my desktop. I tried with and without Essential mod, and it made no difference.

I still have the issue, even without Wilder Wild installed. However, WW was the only one that exhibited the issue on random servers, like Hypixel. Even with Biomes O' Plenty installed, I didn't see anything odd on the Hypixel server.
I'm guessing WW changes the registry/ID for an early entry, but SIHYTCAD will probably be incompatible with any mod that adds (a lot of) blocks.

**Most importantly**, this issue only occurs with SIHYWTCAMD 1.10.4. I reverted to 1.10.3, and didn't notice any problems. If I had to guess, it probably has something to do with porting to 1.21.1, but I haven't tested anything on that version of Minecraft.

I have attached the logs (hopefully they're the right ones), but it may be more helpful to just reproduce it, or even to just mark 1.10.14 as incompatible with 1.21.

Thanks for your help.

**Comment by charlyb01** [comment]
I don't know how you setup your server, but you're either doing it wrong or not installing only Difficulty and Biomes o Plenty. I did the test again and it works perfectly fine when joining a Fabric server that has the same mods and config than the client.

The 1.10.4 version is absolutely not incompatible with 1.21 as it was made for this version. Minecraft 1.21.1 has nothing to do with it, it's just a minor version that only added a hotfix for an important bug.

Feel free to share your server setup here, so I can eventually tell you what's wrong and/or understand the issue, as I can't reproduce it for now

**Comment by charlyb01** [comment]
Keep me in touch :)

**Comment by Toimis** [comment]
Sorry for the lack of progress, but my friends stopped playing Minecraft, so I did too. If I come back to it sometime, I will probably be using your mod again and I'll let you know if I have any issues then since many mods will be updated then.

Not sure if anyone else is having this particular issue with 1.10.4 in 1.21, so you can keep it open to see if anyone else replies or you can close it. Thanks for your help anyways!
