### ISSUE TITLE
Bug When Used with Biomes O Plenty Fabric 1.21

### ISSUE THREAD

**Issue by Sugar-Pink** [sf-inc/sihywtcamd#58]
Using the latest version of this mod alongside the latest version of Biomes O Plenty makes BOP blocks glitch. Wrong blocks will be used in place of other blocks, examples being (leaves filled with water, grass blocks turning into random stair blocks, and logs generating from trees facing the wrong direction alongside a lot of other just incorrect blocks in the BOP biomes. I know for certain its this mod, I tested it out until I narrowed it down to this one. Just wanted to let you know. Not sure if this is a BOP mod issue or an issue on this mods end. 
**EXAMPLES VVV**
![Screenshot 2024-08-21 145046](https://github.com/user-attachments/assets/23cae2af-941e-475b-8301-4b759a6ac4ba)
![Screenshot 2024-08-21 145905](https://github.com/user-attachments/assets/46dde3c1-4ecc-43b7-a678-a69c895f2236)

**Comment by charlyb01** [comment]
Hi, thanks for the report! This seems the exact same issue reported in #57. I'll close this one but I'll investigate the issue asap as it's an all quite annoying issue. Sorry for the inconvenience!

**Comment by charlyb01** [comment]
I got a few questions though
* Does it happen on singleplayer?
* Is it only on terrain generation or also when placing modded blocks?
* Minecraft, Fabric Loader, Fabric API, Difficulty and BOP versions?

**Comment by Sugar-Pink** [comment]
> I got a few questions though
> 
> * Does it happen on singleplayer?
> * Is it only on terrain generation or also when placing modded blocks?
> * Minecraft, Fabric Loader, Fabric API, Difficulty and BOP versions?

Minecraft 1.21
Fabric Loader 0.16.0
BOP 21.0.0.18
Fabric API 0.102.0+1.21

It does **NOT** happen on singleplayer, **ONLY** on server when I tested it. 
Its on terrain generation **AND** when placing modded blocks!
