### ISSUE TITLE
[FEATURE REQUEST] Add an option to disable zombieBuffedProtection for Drowned only

### ISSUE THREAD

**Issue by Footage2-Amply-Pounce** [sf-inc/sihywtcamd#6]
I enjoy the fact that regular zombies take an extra step to defeat now, but not a fan of the drowned having the same buff. They are always in the water, making it impossible to light them on fire, which is just tedious to deal with.

**Comment by charlyb01** [comment]
That totally makes sense! Thanks for the suggestion, I will add an option or change something about drowned soon then
