### ISSUE TITLE
Occasional crash with ModernFix (Which locks you out of the world)

### ISSUE THREAD

**Issue by MrBl4ckSkull** [sf-inc/sihywtcamd#61]
Not sure what causes the crash, but sometimes, seemingly completely randomly while playing on a world, you'll get disconnected with the error "Network Protocol Error" even though you're playing single player. Attempting to reconnect to the world forces it to disconnect you again with the same error, essentially making that world inaccessible until you remove either this mod or Modern Fix.

**Comment by charlyb01** [comment]
Hi, thanks for the report. I'll try to investigate the cause of the issue as soon as I can
