### ISSUE TITLE
Enhancement: Maximum Range for Enderman Blindness

### ISSUE THREAD

**Issue by T0paz** [sf-inc/sihywtcamd#8]
When exploring areas with large Enderman concentration such as the End, blindness can come into effect just by passing your crosshair over an Enderman's head, even if they're very far away. I think this difficulty option would be better if it triggered only if the player is within 64 blocks (requirement for Enderman to become aggro) or only when the Enderman becomes aggro in the first place.

**Comment by charlyb01** [comment]
Hey, thanks for the report! I actually did notive that we can get the effect without aggro the enderman (which is weird as I implemented it in the same place). I didn't know the requirement for aggro is 64 blocks. I may add this condition also, thanks =)
